pipeline:
  setup:
    image: alpine:3.4
    when:
      event: push
      branch: master
    commands:
    - apk update && apk add zip && apk add nodejs
    - npm install nodemailer axios aws-sdk
    - zip -r handler.zip handler.js node_modules package-lock.json

  deploy:
    image: plugins/s3
    secrets:
      - source: aws_access_key
        target: AWS_ACCESS_KEY_ID
      - source: aws_secret_key
        target: AWS_SECRET_ACCESS_KEY
    when:
      event: push
      branch: master
    bucket: infomail-prod
    source: ./handler.zip
    target: /handler/
    region: eu-west-1

  deploy-lambda:
    image: omerxx/drone-lambda-plugin
    secrets:
      - source: aws_access_key
        target: AWS_ACCESS_KEY_ID
      - source: aws_secret_key
        target: AWS_SECRET_ACCESS_KEY
    pull: true
    function_name: infomail
    s3_bucket: infomail-prod
    file_name: handler/handler.zip
    region: eu-west-1

  
