pipeline:

  setup:
    image: node:11
    when:
      event: push
      branch: drone-test
    commands:
    - npm install nodemailer axios aws-sdk
    - apk update && apk add zip
    - zip -r handler.zip handler.js node_modules package-lock.json

  deploy:
    image: plugins/s3
    secrets:
      - source: aws_access_key
        target: AWS_ACCESS_KEY_ID
      - source: aws_secret_key
        target: AWS_SECRET_ACCESS_KEY
    when:
      event: push
      branch: master
    bucket: infomail-prod
    source: ./*
    target: /handler/
    region: eu-west-1

  
