kind: pipeline
name: default

steps:
- name: upload
  image: plugins/s3
  settings:
    bucket: infomail-prod
    access_key:
      from_secret: aws_access_key
    secret_key:
      from_secret: aws_secret_key
    source: public/**/*
    target: /infomail/