pipeline:
  deploy:
    image: plugins/s3
    secrets:
      - source: aws_access_key
        target: AWS_ACCESS_KEY_ID
      - source: aws_secret_key
        target: AWS_SECRET_ACCESS_KEY
    when:
      event: push
      branch: drone-test
      status: success
    bucket: infomail-prod
    source: ./
    target: /
    acl: public-read
    region: eu-west-1
