pipeline:

  setup:
    image: node:11
    when:
      event: push
      branch: drone-test
    commands:
    - npm install nodemailer axios aws-sdk

  
  build:
    image: plugins/s3
    secrets:
      - source: aws_access_key
        target: AWS_ACCESS_KEY_ID
      - source: aws_secret_key
        target: AWS_SECRET_ACCESS_KEY
    when:
      event: push
      branch: master
    bucket: infomail-prod
    source: ./*
    target: /handler/
    region: eu-west-1

  deploy:
    image: python:2.7-alpine
    commands:
    - zip -r handler.zip .

  
